/**
 * AUTOGENERATED VIA openwrt-docs4ai
 * Target: Language Server Protocol (LSP) IDE Autocomplete
 */

declare module "fs" {
    export function readfile(path: any);
    export function writefile(path: any, data: any);
}
