"""
Purpose: Generates TypeScript declaration files (.d.ts) for ucode.
Phase: Indexing
Layers: L3
Inputs: OUTDIR/cross-link-registry.json or OUTDIR/.L2-semantic/ucode/
Outputs: OUTDIR/ucode/ucode.d.ts
Environment Variables: OUTDIR
Dependencies: lib.config
Notes: Strictly for the ucode module. Groups symbols by their base module (e.g. fs, uloop).
"""

import os
import json
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))
from lib import config

sys.stdout.reconfigure(line_buffering=True)

OUTDIR = config.OUTDIR
REGISTRY_PATH = os.path.join(OUTDIR, "cross-link-registry.json")

print("[06c] Generating ucode.d.ts IDE schemas")

if not os.path.isfile(REGISTRY_PATH):
    print(f"[06c] FAIL: cross-link-registry.json not found at {REGISTRY_PATH}")
    sys.exit(1)

try:
    with open(REGISTRY_PATH, "r", encoding="utf-8") as f:
        registry = json.load(f)
except Exception as e:
    print(f"[06c] FAIL: Could not parse registry: {e}")
    sys.exit(1)

# Filter for ucode symbols only
# Symbols in the registry have relative_target like "../ucode/..."
ucode_symbols = {}
for sym, meta in registry.get("symbols", {}).items():
    if "/ucode/" in meta.get("relative_target", ""):
        ucode_symbols[sym] = meta

if not ucode_symbols:
    print("[06c] INFO: No ucode symbols found in registry. Skipping .d.ts generation.")
    sys.exit(0)

# Group by base module (e.g., 'fs' from 'fs.open')
modules = {}
for sym, meta in ucode_symbols.items():
    if "." in sym:
        mod_name, func_name = sym.split(".", 1)
    else:
        mod_name = "global"
        func_name = sym
    
    if mod_name not in modules:
        modules[mod_name] = []
    
    modules[mod_name].append({
        "name": func_name,
        "sig": meta.get("signature", f"{func_name}()"),
        "returns": meta.get("returns", "any")
    })

# Construct .d.ts content
dts_lines = [
    "/**",
    " * AUTOGENERATED VIA openwrt-docs4ai",
    " * Target: Language Server Protocol (LSP) IDE Autocomplete",
    " */",
    ""
]

for mod_name, funcs in sorted(modules.items()):
    if mod_name == "global":
        for f in sorted(funcs, key=lambda x: x["name"]):
            dts_lines.append(f"declare function {f['name']}(...args: any[]): {f['returns']};")
    else:
        dts_lines.append(f'declare module "{mod_name}" {{')
        for f in sorted(funcs, key=lambda x: x["name"]):
            # Normalize signature for simple TS: foo(a, b) -> foo(a: any, b: any)
            # This is a very rough heuristic for v12
            sig = f['sig']
            if "(" in sig and ")" in sig:
                params_str = sig.split("(", 1)[1].rsplit(")", 1)[0]
                if params_str.strip():
                    params = [p.strip() for p in params_str.split(",")]
                    sig_ts = f"{f['name']}({', '.join([f'{p}: any' for p in params])})"
                else:
                    sig_ts = f"export function {f['name']}(): {f['returns']};"
            else:
                sig_ts = f"export function {f['name']}(...args: any[]): {f['returns']};"
            
            # If we didn't use the 'export function' prefix yet
            if not sig_ts.startswith("export function"):
                sig_ts = f"export function {sig_ts};"
            
            dts_lines.append(f"    {sig_ts}")
        dts_lines.append("}")
    dts_lines.append("")

out_dir = os.path.join(OUTDIR, "ucode")
os.makedirs(out_dir, exist_ok=True)
out_path = os.path.join(out_dir, "ucode.d.ts")

with open(out_path, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(dts_lines))

print(f"[06c] OK: {out_path} ({len(ucode_symbols)} symbols)")
